services:
  - type: web
    name: d-team-solver
    runtime: python
    rootDir: ./
    buildCommand: pip install -r webapp/requirements.txt
    startCommand: cd webapp && gunicorn app:app --bind 0.0.0.0:$PORT --timeout 600
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.6"
